import { allKeys } from "../flattened/all_keys.js"
import { testCallJsonify } from "../flattened/test_call_jsonify.js"

testCallJsonify(allKeys, null)
testCallJsonify(allKeys, true)
testCallJsonify(allKeys, 5)
testCallJsonify(allKeys, {})
testCallJsonify(allKeys, {a:1})
testCallJsonify(allKeys, {a:1, b:2})
testCallJsonify(allKeys, new Date())
testCallJsonify(allKeys, new Error())
testCallJsonify(allKeys, new Set())
testCallJsonify(allKeys, new Set([1,2,3]))
testCallJsonify(allKeys, new Map())
testCallJsonify(allKeys, new Map([[1,2],[3,4]]))
testCallJsonify(allKeys, new ArrayBuffer())
testCallJsonify(allKeys, new ArrayBuffer(10))
testCallJsonify(allKeys, new Int8Array())
testCallJsonify(allKeys, new Int8Array(10))
testCallJsonify(allKeys, new Uint8Array())
testCallJsonify(allKeys, new Uint8Array(10))
testCallJsonify(allKeys, new Uint8ClampedArray())
testCallJsonify(allKeys, new Uint8ClampedArray(10))
testCallJsonify(allKeys, new Int16Array())
testCallJsonify(allKeys, new Int16Array(10))
testCallJsonify(allKeys, new Uint16Array())
testCallJsonify(allKeys, new Uint16Array(10))
