#!/usr/bin/env -S deno run --allow-all

import { FileSystem, Console } from "https://deno.land/x/file_system_js@0.4.1/main/deno.js"
import { run, Timeout, Env, Cwd, Stdin, Stdout, Stderr, Out, Overwrite, AppendTo, throwIfFails, returnAsString, zipInto, mergeInto } from "https://deno.land/x/sprinter@0.4.2/index.js"

const argsWereGiven = Deno.args.length > 0

for (const each of await FileSystem.listItemsIn("./tests")) {
    if (each.isFile && each.extension === ".js") {
        if (argsWereGiven) {
            // skip files that were not mentioned
            if (!Deno.args.includes(each.basename) && !Deno.args.includes(each.name)) {
                continue
            }
        }
        const output = await run('deno', 'run', '--allow-all', each.path, Out(returnAsString))
        const pureText = Console.clearColorsFrom(output)
        FileSystem.write({data: pureText, path: each.path+".log" })
    }
}